### ISSUE TITLE
Netty resource handler doesn't work with jar-based files

### ISSUE THREAD

**Issue by tekul** [unfiltered/unfiltered#131]
As described in this thread:

https://groups.google.com/forum/?pli=1#!topic/unfiltered-scala/hp4k9SHMNOo

The netty server static resource plan attempts to load a resource as a java.io.File instance, which won't work when the resources are being server from an embedded jar.

**Comment by noblecraft** [comment]
has this regressed since 0.7?

I'm running 0.8.1, can load jar resources using the method used in https://github.com/n8han/pamflet/blob/master/library/src/main/scala/shared.scala 
to load resources from jar.
