### ISSUE TITLE
Upgrade specs2

### ISSUE THREAD

**Issue by rgladwell** [unfiltered/unfiltered#302]
The specs2 dependency for Unfiltered is stale and includes bugs such as the following:

https://github.com/etorreborre/specs2/issues/325

It would be great to update to the latest version of spec2.

**Comment by chrislewis** [comment]
It's true, things have languished a bit. Any interest in submitting a pull request? There's nothing like fresh contributions to jump start the engine!

**Comment by rgladwell** [comment]
I did try but I kept getting dependency issues.

**Comment by peel** [comment]
Already submitted one. See #306

**Comment by chrislewis** [comment]
@peel +1
