### ISSUE TITLE
Can't find MemoryAwareThreadPoolExecutor

### ISSUE THREAD

**Issue by mfirry** [unfiltered/unfiltered#317]
I must be missing some dependencies.

Here's what I got:

```
  "net.databinder" %% "unfiltered-netty-server",
  "net.databinder" %% "unfiltered-netty",
  "net.databinder" %% "unfiltered-json4s"
```

Do I specifically need to depend on `netty`? If so, what bundle and version?

Thanks.

**Comment by omarkilani** [comment]
MemoryAwareThreadPoolExecutor was part of netty 3, which hasn't been supported in a while.

* https://github.com/netty/netty/wiki/New-and-noteworthy-in-4.x#wiki-well-defined-thread-model
* http://stackoverflow.com/questions/16046283/netty-4-code-to-run-blocking-operations-in-thread-pool

**Comment by ashawley** [comment]
Indeed, the last time Netty 3 was included was unfiltered 0.7.1.

**Comment by ashawley** [comment]
The documentation mentions it still:

http://unfiltered.ws/10/b.html

**Comment by omarkilani** [comment]
Yup. I'm still thinking about what to replace that with that's generic enough.

The problem is quite difficult... :/
