### ISSUE TITLE
support Scala 2.12

### ISSUE THREAD

**Issue by xuwei-k** [unfiltered/unfiltered#319]
- [ ] tubesocks https://github.com/softprops/tubesocks/pull/5
- [x] dispatch

**Comment by mfirry** [comment]
Also maybe [specs2](https://github.com/etorreborre/specs2/issues/519), right?

**Comment by hamnis** [comment]
Dispatch cannot be upgraded since it has a dependency to unfiltered which in turns depends on unfiltered.

Both for tests.

I suggest dropping dispatch for tests and instead go for either AHC directly, or maybe OkHttp.

**Comment by hamnis** [comment]
Additional upgrades needed:

- [scalatest]
- [json4s]

**Comment by SethTisue** [comment]
if Unfiltered is now available for 2.12, can someone submit a PR on https://github.com/scala/make-release-notes/blob/2.12.x/projects-2.12.md removing it from the list at the bottom and adding it to the list at the top...?

**Comment by omarkilani** [comment]
@SethTisue is it okay if the version is "0.9.0-beta2"?

**Comment by SethTisue** [comment]
sure

**Comment by hamnis** [comment]
https://github.com/scala/make-release-notes/pull/251
