### ISSUE TITLE
New commiters to move project forward?

### ISSUE THREAD

**Issue by hamnis** [unfiltered/unfiltered#320]
Hello all.

Just wondering if there should be more people added to the organization to move  the project forward. It seems like @n8han and @softprops are no longer interested in Unfiltered =(

I really hope we, as a community, can step up and help.

**Comment by mfirry** [comment]
Sounds like something for @eed3si9n and the @foundweekends project :)

**Comment by oyvindberg** [comment]
Good initiative, @hamnis . I've been wondering for the longest time if there is anybody around to merge patches.

**Comment by softprops** [comment]
I like the spirit of this. Meetup still actively uses and relies on unfiltered for many of its services both old and new so I know we'd benefit from this proposal. Unfiltered was something of a pet project for me to work on in my free time on the weekends but Im finding I have less and less free time to reliably devote to the project these days. The project is already under and organization which is a great start. I'd be happy to have more folks drive the project forward in the same spirit of @foundweekends. Im not sure what needs to happen next in order to make that happen. I think @n8han has the publishing credentials.

**Comment by xuwei-k** [comment]
> more people added to the organization

+1

**Comment by eed3si9n** [comment]
To kickstart the organization again, you'd need two ~ three medium motivated people who can together spend a few hours each week to triage issues, review PRs, and come up with the general direction. That's just project management, not counting in the coding.

If it's beneficial for some companies to have Unfiltered maintained, they should assign a person to spend 1h a week.

**Comment by hamnis** [comment]
Publishing credentials can resolved by publishing under a new domain. 

unfiltered.ninja
unfiltered.gratis

or a plethora of other options.

**Comment by benhutchison** [comment]
My employer, REA Group, are significant users of Unfiltered. PR #299 acknowledges that. 

Internally we have been discussing how to maintain our existing Unfiltered-based systems, and what our future direction should be, over the past few weeks.

I think we could contribute 1 or 2 maintainers with a time allocation towards upkeep.

**Comment by maiflai** [comment]
Hi,

I've been doing some work to upgrade the dispatch/reboot library to Netty 4 with a view to publishing it under a different group id (it's in a similar state to Unfiltered).

I tried to upgrade to Scala 2.12 and found that it has a dependency on Unfiltered for testing; it sounds as though we have something of a circular dependency? 

I wondered if it might be sensible to merge them into a single repository to resolve this. I'm happy to lend a hand.

Thanks,
Stu

**Comment by hamnis** [comment]
I am trying to fix unfiltered to get rid of the dispatch test-dependency. PR should come soon.

**Comment by hamnis** [comment]
@softprops are you an owner of the organisation? or is it just @n8han  ?

**Comment by omarkilani** [comment]
I'd just like to throw in that we (Remember The Milk) are also interested in helping maintain unfiltered going forward. We have a branch using netty 4.1.

**Comment by eed3si9n** [comment]
Nice. So we have REA Group and Remember The Milk.
All we have to do is add you folks on the organization.

**Comment by omarkilani** [comment]
Don't forget @hamnis  :)

**Comment by softprops** [comment]
Ok, I'd like to get this rolling ( and not be a road blocker ) so just sent out some invites to giving @hamnis and @eed3si9n owner powers. From there they should have the power to add collaborators and manage teams and what not. enjoy!

**Comment by eed3si9n** [comment]
Awesome. Thanks, Doug!

**Comment by eed3si9n** [comment]
Invited @benhutchison and @xuwei-k.

**Comment by hamnis** [comment]
what some great news to wake up to. Thanks Doug!
