### ISSUE TITLE
old giter8 templates in README

### ISSUE THREAD

**Issue by xuwei-k** [unfiltered/unfiltered#346]
I have updated all g8 templates in unfiltered organization.

- https://github.com/unfiltered/unfiltered-gae.g8/commit/00541a458b133666b3
- https://github.com/unfiltered/coffee-filter.g8/commit/b81d992c20ccc8f06
- https://github.com/unfiltered/unfiltered.g8/commit/61e73a2c85326594bf0a
- https://github.com/unfiltered/unfiltered-slick.g8/commit/2a3ef7fa54268595
- https://github.com/unfiltered/unfiltered-war.g8/commit/dc60692816a0644c1
- https://github.com/unfiltered/unfiltered-scalate.g8/commit/92434192fb0cbf852c92
- https://github.com/unfiltered/unfiltered-netty.g8/commit/204e8a6778da70b39a3

README refer following non unfiltered org templates.
- https://github.com/softprops/unfiltered-websockets.g8
- https://github.com/softprops/unfiltered-oauth-server.g8

should we
- just remove the links from `README` ?
- or fork to unfiltered organization (or transfer from @softprops ) and maintenance these g8 templates? (I don't have the authority create new repository in unfiltered organization)

**Comment by hamnis** [comment]
We can fork the repos. thereby keeping the link to @softprops . I'll find some time to do this today.

**Comment by hamnis** [comment]
@xuwei-k I have forked the repos into the organization, and added write access.

**Comment by xuwei-k** [comment]
Thanks! I'll update these templates.

**Comment by xuwei-k** [comment]
I could not push to `unfiltered/unfiltered-websockets.g8` and `unfiltered/unfiltered-oauth-server.g8` 😕 

![2016-12-02 20 15 49](https://cloud.githubusercontent.com/assets/389787/20832190/2b961642-b8cc-11e6-9a8d-e9ac05b3a7c6.png)


Could anyone please enable travis-ci for  `unfiltered/unfiltered-websockets.g8` and `unfiltered/unfiltered-oauth-server.g8` ?

**Comment by xuwei-k** [comment]
Oh, we need https://github.com/softprops/unfiltered-oauth-client.g8 if we use https://github.com/unfiltered/unfiltered-oauth-server.g8#usage .
Could anyone please fork `softprops/unfiltered-oauth-client.g8` to unfiltered org as well?

**Comment by hamnis** [comment]
I was sure they where write. Sorry.
Fixed now.

Will enable travis as well.

**Comment by hamnis** [comment]
Travis is enabled.

**Comment by eed3si9n** [comment]
I've bumped Yoshida-san (@xuwei-k)'s role to Owner on the Unfiltered organization. I job is done here :)
