### ISSUE TITLE
new groupId

### ISSUE THREAD

**Issue by hamnis** [unfiltered/unfiltered#351]
We need to use a new maven groupId for unfiltered.

@omarkilani har already purchased `unfiltered.ws` for a possible new groupId.

Otherwise we might just go for `com.github.unfiltered`

Hosting the docs should just be done on github pages anyway, adding CNAME is an easy thing.

**Comment by eed3si9n** [comment]
👍  for `unfiltered.ws`. Samoan people sounds like peaceful people.

**Comment by omarkilani** [comment]
+1 for unfiltered.ws. :)

**Comment by hamnis** [comment]
https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=21&pid=10134

My sonatype username is : hamnis

I can register with OSS if people provide their oss.sonatype.org usernames.

**Comment by eed3si9n** [comment]
My Sonatype username is eed3si9n.

**Comment by omarkilani** [comment]
My sonatype username is omar

**Comment by xuwei-k** [comment]
My sonatype username is [xuwei-k](https://issues.sonatype.org/secure/ViewProfile.jspa?name=xuwei-k)

**Comment by hamnis** [comment]
https://issues.sonatype.org/browse/OSSRH-26768

@omarkilani You might need to confirm the ownership of the domain.

**Comment by benhutchison** [comment]
My sonatype username is benhutchison

**Comment by hamnis** [comment]
Publishing rights has been assigned to me, @omarkilani, @eed3si9n and @xuwei-k 

We should maybe cut a new beta today?

**Comment by omarkilani** [comment]
+1 for cutting a new beta.

**Comment by omarkilani** [comment]
@benhutchison added to sonatype!
