### ISSUE TITLE
compile example codes in docs

### ISSUE THREAD

**Issue by xuwei-k** [unfiltered/unfiltered#353]
Maybe there are some outdated codes in https://github.com/unfiltered/unfiltered/tree/0.9.0/docs

- use [sbt-pamflet](https://github.com/sbt/sbt-pamflet)
- or migrate another tool
  - [paradox](https://github.com/lightbend/paradox) https://twitter.com/xuwei_k/status/805814506467139584
  - or something else

WDYT?

**Comment by hamnis** [comment]
Paradox looks nice.

**Comment by xuwei-k** [comment]
@eed3si9n Do you have any opinions? I tried sbt-pamflet but there are some issues. https://github.com/sbt/sbt-pamflet/issues

**Comment by omarkilani** [comment]
Paradox looks great @xuwei-k

**Comment by eed3si9n** [comment]
I'm involved with both the projects, so it's hard for me to chose.
If ppl like Paradox, I guess we can try that first. Paradox does have the ability so include snippets, whereas sbt-pamflet (when wired with a local SNAPSHOT) can compile included source and output REPL result.

**Comment by omarkilani** [comment]
I don't have a preference either way. Whatever @xuwei-k wants. :)

**Comment by xuwei-k** [comment]
I'll try some tools and auto publish plugin([sbt-site](https://github.com/sbt/sbt-site), [sbt-ghpages](https://github.com/sbt/sbt-ghpages) etc)  to github pages on this weekend.
