### ISSUE TITLE
Update docs for netty 4.x

### ISSUE THREAD

**Issue by omarkilani** [unfiltered/unfiltered#362]
See https://github.com/unfiltered/unfiltered/issues/317

https://github.com/unfiltered/website/blob/master/src/paradox/10/b.md#deference-has-its-memory-limits still references MemoryAwareThreadPoolExecutor.

This no longer exists in netty 4.x. There's no replacement functionality.

We need to provide an example to people on how to run a netty cycle based service without it running out of memory/dying.

**Comment by hamnis** [comment]
Seems related: http://stackoverflow.com/questions/16046283/netty-4-code-to-run-blocking-operations-in-thread-pool
