### ISSUE TITLE
SslServerSpec test fails in Scala 2.12 community build

### ISSUE THREAD

**Issue by SethTisue** [unfiltered/unfiltered#364]
at e.g. https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/1131/consoleFull we see unfiltered.netty.SslServerSpec failing

I disabled running unfiltered's tests so that it can still be included in the community build. it would be better if we could run them, though. maybe it's an Oracle vs OpenJDK thing?

**Comment by hamnis** [comment]
seems like this is an openjdk vs oracle thing.

**Comment by SethTisue** [comment]
seems to have gotten fixed somehow... we are running unfiltered's tests again and I'm not seeing this

**Comment by SethTisue** [comment]
seen again at https://scala-ci.typesafe.com/job/scala-2.12.x-integrate-community-build/2547/consoleFull

**Comment by SethTisue** [comment]
is this believed to be fixed on the 0.10.x branch?

**Comment by omarkilani** [comment]
I think so, yes.

**Comment by SethTisue** [comment]
okay, we can reopen if I see it again
