### ISSUE TITLE
Upgrade jetty to 9.4

### ISSUE THREAD

**Issue by hamnis** [unfiltered/unfiltered#384]
To be able to support HTTP/2 we should upgrade jetty to 9.4

**Comment by omarkilani** [comment]
Would need to ditch JDK 7 support for this, so Scala 2.10 would be out.

Which is fine by me.

**Comment by eed3si9n** [comment]
What that be considered a breakage on binary compatibility? If so what's the versioning policy?

**Comment by omarkilani** [comment]
@eed3si9n this would be for the 0.10.x series so it should be fine?

We can keep doing 0.9.x releases too to bump netty etc.

**Comment by eed3si9n** [comment]
Here's https://mvnrepository.com/artifact/ws.unfiltered/unfiltered-filter_2.10/usages.
I recently used it to test my HTTP library, which is available for JDK 7 and Scala 2.10 - https://github.com/eed3si9n/gigahorse

**Comment by eed3si9n** [comment]
Also the recent versions of Scala 2.10 should work with JDK 8.

**Comment by omarkilani** [comment]
Oh, if that's the case then we should be fine? Just tell people to update their JDK and bump Scala to the latest 2.10.x?

**Comment by eed3si9n** [comment]
It's up to each project to consider JDK bump as API breakage or not.
sbt 0.13 for example is still on JDK 6 because of the requirement.

**Comment by omarkilani** [comment]
Okay, so why not have to release 'streams'?

We can keep 0.9.x on JDK 7 / old Scala 2.10.
We can do a new 0.10.x (or whatever) stream on JDK 8 / new Scala 2.10.

Then people can choose to 'upgrade' streams once they're ready or whatever?

**Comment by eed3si9n** [comment]
That would be the best option if the maintainers are willing to support two branches.
I think it's reasonable that when 0.10.x comes out Scala 2.10 support gets dropped, and start prepping for Scala 2.13.x instead.

**Comment by hamnis** [comment]
lets drop 2.10 in 0.10.x. 
if there is a strong backlash we can consider re-adding or backport things.

**Comment by omarkilani** [comment]
Closed by https://github.com/unfiltered/unfiltered/pull/400
