### ISSUE TITLE
avoid deprecated API since Java 9

### ISSUE THREAD

**Issue by xuwei-k** [unfiltered/unfiltered#397]
### javax.activation

> @Deprecated(since="9", forRemoval=true)
>
> Module java.activation
> Deprecated, for removal: This API element is subject to removal in a future version.

- https://docs.oracle.com/javase/9/docs/api/java.activation-summary.html
- https://github.com/unfiltered/unfiltered/blob/0.9.1/util/src/main/scala/mime.scala#L23
- https://github.com/unfiltered/unfiltered/blob/0.9.1/netty-server/src/main/scala/resources.scala#L22

any others? 🤔

**Comment by xuwei-k** [comment]
https://github.com/unfiltered/unfiltered/pull/407

**Comment by SethTisue** [comment]
#407 was merged. should this issue be closed?
