### ISSUE TITLE
test suite intermittently hangs in Scala community build

### ISSUE THREAD

**Issue by SethTisue** [unfiltered/unfiltered#399]
I've seen this a number of times now. latest occurrence: https://scala-ci.typesafe.com/view/scala-2.12.x/job/scala-2.12.x-integrate-community-build/2580/consoleFull

I will disable the tests in the `unfiltered-oauth2` subproject and see if it helps

**Comment by hamnis** [comment]
@SethTisue Can you change the base branch to 0.10.x instead of 0.9.x ? I think the build should be fine now.

**Comment by SethTisue** [comment]
tracking 0.10.x now, re-enabled all tests, we'll see how it goes: scala/community-builds@ddcec4320a9e14cd22472e2a3fbb2c4864627cf8

(first run was green, at least!)

closing, I'll reopen if problems start up again
