### ISSUE TITLE
NoClassDefFoundError: io/netty/channel/kqueue/KQueueEventLoopGroup

### ISSUE THREAD

**Issue by Sciss** [unfiltered/unfiltered#450]
Hi there. Looking for a Scala 2.13.0-RC2 build. I see a version for Scala 2.13.0-RC1 was published, 0.10.0-M3, but it seems to have a problem; in dispatch/reboot I always get these:

    java.lang.NoClassDefFoundError: io/netty/channel/kqueue/KQueueEventLoopGroup

which doesn't happen when using 0.10.0-M2 (ends with Scala 2.13.0-M5). Any ideas if this is a bug in the published artifact? Seems something got messed up in your pom file, for example I see this entry in 0.10.0-M3 not 0.10.0-M2:

    <dependency>
        <groupId>io.netty</groupId>
        <artifactId>netty-transport-native-kqueue</artifactId>
        <version>4.1.13.Final</version>
        <classifier>osx-x86_64</classifier>
    </dependency>

So that would mean it only shows up in OS X I guess? The published artifact 0.10.0-M2 does not contain platform specific dependencies and doesn't cause issues.

**Comment by omarkilani** [comment]
Hi @Sciss

What build system are you using?

**Comment by Sciss** [comment]
I'm building dispatch/reboot with Scala (2.11, 2.12, 2.13.0-RC), that's on Linux (Debian) using OpenJDK 8.

**Comment by omarkilani** [comment]
Ok... I’m not sure why you’d see that error of the top of my head, but our test suite runs on that exact config without issues.

We also run this in production on Linux, but I need to take a look at sbt’s dependency tree.

Maybe we just need to publish for -RC2.

**Comment by Sciss** [comment]
> Maybe we just need to publish for -RC2.

That would be great. Since there is no issue on your side, It might be an issue with the way dependencies are filtered in dispatch (in that case sorry for raising a false alarm). I will investigate. Closing for now.
