### ISSUE TITLE
Add Support for Matrix Parameters

### ISSUE THREAD

**Issue by ClintCombs** [unfiltered/unfiltered#65]
It would be nice to add support for parsing URI matrix parameters.  JAX-RS currently supports this via the @MatrixParam annotation.  It is used to inject matrix parameters that have been parsed out of the URL.

For example, consider some REST resources that allows a client to search for sites within a certain number of miles of a given latitude and longitude looking for people that work at the sites and meet some minimum age criteria.  The @MatrixParam provides an easy way to extract lat, lon, withinMiles, and minAge from these URLs.  The first example provides access to sites while the second provides access to employees.

http://example.com/sites;lat=30.25;lon=-81.1;withinMiles=10
http://example.com/sites;lat=30.25;lon=-81.1;withinMiles=10/employees;minAge=20

As Nathan suggested on the mailing list this might be relatively easy to achieve in Unfiltered using a regex or parser combinator.

**Comment by noblecraft** [comment]
I'm looking for this feature too.
